services:

  prometheus:
    image: prom/prometheus:latest
    container_name: temperature_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    expose:
      - 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  exporter:
    image: ghcr.io/tomas-petrauskas/onewire-prometheus-exporter:latest
    restart: unless-stopped
    container_name: temperature_exporter
    expose:
      - 8105
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices

volumes:
  prometheus_data: